# Generated by Django 2.1.7 on 2019-03-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0002_filesrecorder_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesrecorder',
            name='content_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
