# Generated by Django 2.1.7 on 2019-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0003_filesrecorder_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesrecorder',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
