# Generated by Django 2.1.7 on 2019-03-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0004_filesrecorder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesrecorder',
            name='file_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
