# Generated by Django 2.1.7 on 2019-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0005_filesrecorder_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesrecorder',
            name='file_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filesrecorder',
            name='content_type',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
