# Generated by Django 2.1.7 on 2019-03-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0006_auto_20190307_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesrecorder',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
