# Generated by Django 2.1.7 on 2019-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0007_auto_20190308_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesrecorder',
            name='hased_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filesrecorder',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
    ]
