# Generated by Django 2.1.7 on 2019-03-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0008_auto_20190308_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesrecorder',
            old_name='hased_name',
            new_name='hashed_name',
        ),
    ]
