# Generated by Django 2.1.7 on 2019-03-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0011_sharingrecorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharingrecorder',
            old_name='file_id',
            new_name='file',
        ),
    ]
