# Generated by Django 2.1.7 on 2019-03-12 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_app', '0012_auto_20190311_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingrecorder',
            name='sharer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sharer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
