# Generated by Django 2.1.7 on 2019-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0013_sharingrecorder_sharer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingrecorder',
            name='private_flag',
            field=models.BooleanField(default=True),
        ),
    ]
