# Generated by Django 2.1.7 on 2019-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0014_sharingrecorder_private_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingrecorder',
            name='private_flag',
            field=models.BooleanField(default=False),
        ),
    ]
