# Generated by Django 2.1.7 on 2019-03-12 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0015_auto_20190312_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharingrecorder',
            old_name='private_flag',
            new_name='is_private_sharing',
        ),
        migrations.AddField(
            model_name='sharingrecorder',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
