# Generated by Django 2.1.7 on 2019-03-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0016_auto_20190312_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesrecorder',
            old_name='user_id',
            new_name='user',
        ),
    ]
