# Generated by Django 2.1.7 on 2019-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0017_auto_20190313_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingrecorder',
            name='deleted_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sharingrecorder',
            name='was_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
