# Generated by Django 2.1.7 on 2019-03-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_app', '0019_filesrecorder_was_in_trashbin'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesrecorder',
            name='deleting_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
