# Generated by Django 2.1.7 on 2019-09-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staruser',
            name='sended_star',
            field=models.IntegerField(default=1),
        ),
    ]
