# Generated by Django 2.1.7 on 2019-09-21 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesRecorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='')),
                ('file_name', models.CharField(max_length=254)),
                ('hashed_name', models.CharField(max_length=40)),
                ('content_type', models.CharField(max_length=80)),
                ('file_type', models.CharField(max_length=30, null=True)),
                ('size', models.CharField(max_length=20, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('deleting_time', models.DateTimeField(default=None, null=True)),
                ('was_in_trashbin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharingRecorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_time', models.DateTimeField(auto_now_add=True)),
                ('is_private_sharing', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField()),
                ('was_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_app.FilesRecorder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
